name: CICD
on:  [push]

jobs:
  Test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-ci-lab

    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: pytest

      - name: Add formating
        run: flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: Test-job

    defaults:
      run:
        working-directory: 01-ci-lab

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
            role-to-assume: arn:aws:iam::770762663048:role/GH_CICD
            aws-region: us-east-1

      - name: Create function
        run: |
          aws create-function \
            --function-name Calculator-app \
            --role arn:aws:iam::770762663048:role/GH_CICD
            --runtime python3.12 \

      - name: Zip Lambda function code
        run: |
          cp app/calculator.py lambda_function.py
          zip function.zip lambda_function.py

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:770762663048:function:Calculator-app \
            --zip-file fileb://function.zip
            